### ISSUE TITLE
Is there anyway to change only certain attribute

### ISSUE THREAD

**Issue by SystemErrorWang** [csmliu/STGAN#12]
Thank you for your excellent work at first
I cloned this repo and followed the readme, everything works fine, and i would like to know if there's anyway to change only one attribute of a face(young to old for example) and generatr only one image?
Thank you for your kind help in advance!

**Comment by csmliu** [comment]
Of course, you can do this by the following command (a special case of `multiple attributes`):
```cmd
python test.py --experiment_name 128 --test_atts Young [--test_ints 1.0] [--img 182638 [182639]]
```
Note that parameters in [] are optional.

**Comment by SystemErrorWang** [comment]
@csmliu Thank you for your quick reply. I run the script following the command you provided, but it still generates 14 images with different attributes changed

**Comment by CastellanLiu** [comment]
I've tested
```cmd
python test.py --experiment_name 128 --test_atts Young --img 182638
```
and the command generates only one image.

**Comment by SystemErrorWang** [comment]
> I've tested
> 
> ```batchfile
> python test.py --experiment_name 128 --test_atts Young --img 182638
> ```
> 
> and the command generates only one image.

I can generate images as expected now, really appreciate your kind help! Thank you soooooooo much!
