### ISSUE TITLE
sth about the att classification

### ISSUE THREAD

**Issue by zhoushiwei** [csmliu/STGAN#13]
Hi , When I use thr att classifcation , it broke at "imgs = np.concatenate(np.split(imgs, 15, axis=2))"  And I also very puzzle at 
       imgs = np.concatenate([imgs[:, :img_size, :], imgs[:, img_size+img_size//10:, :]], axis=1)
        imgs = np.expand_dims(imgs, axis=0)
        imgs = np.concatenate(np.split(imgs, 15, axis=2))

Why should do this?

**Comment by CastellanLiu** [comment]
Well, I'll give some explanations below for the code:
```python
imgs = np.concatenate([imgs[:, :img_size, :], imgs[:, img_size+img_size//10, :]], axis=1)
# this operation removes the black bar between the input image and the output images
# see https://github.com/csmliu/STGAN/blob/2ef612e28673c3f03e8aa28b619a05742e5f8fc4/test.py#L162
imgs = np.expand_dims(imgs, axis=0) # HWC --> NHWC
imgs = np.concatenate(np.split(imgs, 15, axis=2))
# split the image along W(idth) and put them together along the N dimension
# The last two lines are equivalent to
# imgs = np.stack(np.split(imgs, 15, axis=1), axis=0)
```
Maybe you could check the output image format. If you have any other questions, feel free to reopen this issue.

**Comment by zhoushiwei** [comment]
> Well, I'll give some explanations below for the code:
> 
> ```python
> imgs = np.concatenate([imgs[:, :img_size, :], imgs[:, img_size+img_size//10, :]], axis=1)
> # this operation removes the black bar between the input image and the output images
> # see https://github.com/csmliu/STGAN/blob/2ef612e28673c3f03e8aa28b619a05742e5f8fc4/test.py#L162
> imgs = np.expand_dims(imgs, axis=0) # HWC --> NHWC
> imgs = np.concatenate(np.split(imgs, 15, axis=2))
> # split the image along W(idth) and put them together along the N dimension
> # The last two lines are equivalent to
> # imgs = np.stack(np.split(imgs, 15, axis=1), axis=0)
> ```
> 
> Maybe you could check the output image format. If you have any other questions, feel free to reopen this issue.

Hi, csmliu ,Thanks for your nice answer, I have check the image format,the issue is still in "np.split(imgs, 15, axis=2)" and if change the '15' to others , it will ok ,the input image size is 128*128, right?

**Comment by zhoushiwei** [comment]
> Well, I'll give some explanations below for the code:
> 
> ```python
> imgs = np.concatenate([imgs[:, :img_size, :], imgs[:, img_size+img_size//10, :]], axis=1)
> # this operation removes the black bar between the input image and the output images
> # see https://github.com/csmliu/STGAN/blob/2ef612e28673c3f03e8aa28b619a05742e5f8fc4/test.py#L162
> imgs = np.expand_dims(imgs, axis=0) # HWC --> NHWC
> imgs = np.concatenate(np.split(imgs, 15, axis=2))
> # split the image along W(idth) and put them together along the N dimension
> # The last two lines are equivalent to
> # imgs = np.stack(np.split(imgs, 15, axis=1), axis=0)
> ```
> 
> Maybe you could check the output image format. If you have any other questions, feel free to reopen this issue.

Thanks for your nice answer .it's my fault , your input image is from the STGAN output images,  and I input the image size is single face image
