### ISSUE TITLE
您好，想请教一下关于属性的问题？

### ISSUE THREAD

**Issue by ZhengHui-Z** [csmliu/STGAN#14]
怎么指定自己的测试图片，还有就是结果里面变老的属性是什么？
测试的配置文件里面只有这几个属性:
```
"atts":[
        "Bald",
        "Bangs",
        "Black_Hair",
        "Blond_Hair",
        "Brown_Hair",
        "Bushy_Eyebrows",
        "Eyeglasses",
        "Male",
        "Mouth_Slightly_Open",
        "Mustache",
        "No_Beard",
        "Pale_Skin",
        "Young"
    ],
```
还有一个问题是测试的时候为什么还需要调用`list_attr_celeba.txt`文件，这个不应该是训练才要用到的标签吗？

希望得到您的帮助，非常感谢！

**Comment by csmliu** [comment]
1. 指定自己的测试图片：
  可以自己写dataloader，然后在`test.py`中进行相应的修改。此外，还需提供该文件相应的`list_attr.txt`，以确定默认转换方式；或者对`test.py`进行修改以指定属性修改方式。
2. 结果里面变老的属性：
  是`Young`属性，+1代表年轻，-1代表不年轻，即年老。默认情况下，如果测试图片是`+1`，则会往变老转换，如果测试图片是`-1`，则会往变年轻转换
3. 测试时调用`list_attr_celeba.txt`：
  因为需要知道测试图片原本的属性，以便向其相反属性转换。使用时可以不需要`list_attr_celeba.txt`，直接由用户提供如何修改属性（不修改的属性无须提供，默认置零即可）
