### ISSUE TITLE
How to Improve the effect of High Resolution Image

### ISSUE THREAD

**Issue by zhoushiwei** [csmliu/STGAN#16]
Hi, csmliu
At present, the results of training on high-resolution images are not good. Is there any other way to improve the conversion results of high-resolution images, such as 512 or 1024 images?If I add a data set of high resolution images, will it improve the current effect at high resolution?

**Comment by csmliu** [comment]
Sorry I didn't try images with higher-resolution, but the model size may be a problem, and I have to reduce the number of channels when training the 384x384 model.
BTW, are you using low-resolution images to train the model? Using extra images to train the model should lead to a better result, but I can't say how much they can help.

**Comment by zhoushiwei** [comment]
yean ,I also think that adding data and restrict the pose of the face should enhance the effect . But for the size of 512*512 image or larger, it seems difficult to train a robust model. If you make modifications at the algorithm level, do your have any good suggestions?

**Comment by csmliu** [comment]
Maybe you can refer to BigGAN or StyleGAN. Their architectures are designed for HR images, maybe you could get inspired by their work.

**Comment by zhoushiwei** [comment]
ok, Thanks,by the way,Is there a schedule for the pytorch multi-card version?

**Comment by zhoushiwei** [comment]
If you deepen the training network, do you think the effect will be better, or will it be more difficult to converge?

**Comment by csmliu** [comment]
If you train the model from stratch, deepen the network should result in a harder training. Yet you can initialize the model with the pretrained model, maybe this could help.
