### ISSUE TITLE
你好，想请教一下是否可以让标签的差异向量指定为某个属性的差异

### ISSUE THREAD

**Issue by VincentZgj** [csmliu/STGAN#19]
你好，想请教下，在训练之前将训练数据的标签的某一位所代表的属性就行指定的reverse，比如只改变训练数据的眼镜这一位对应的标签，然后他们之间的差异就是眼镜这个属性放进去训练，然后这个模型就指定转换眼镜的差异。我修改的代码如下，但是最终训练效果好像不是太好，不知道是什么原因。在使用验证集数据的时候作了同样的修改，但是最终验证没有效果。
代码：
```python
xa, a = tr_data.get_next()
b=copy.deepcopy(a)
for i in enumerate(b.shape[0]):
    b[i][6] = 1-b[i][6]
# b = tf.random_shuffle(a)#将标签随机打乱
xa = tf.convert_to_tensor(xa)
a = tf.convert_to_tensor(a)
b = tf.convert_to_tensor(b)
_a = (tf.to_float(a) * 2 - 1) * thres_int
_b = (tf.to_float(b) * 2 - 1) * thres_int
```

**Comment by csmliu** [comment]
抱歉更新了下您的问题，把代码格式化了一下。

一个简单的建议是，把数据集以及代码中其他的属性去掉，只保留需要的一项。
此外，您给出的代码看起来是正确的（其中for循环应该可以去掉，用`b[:, 6] = 1 - b[:, 6]`代替），同时建议参考我在`test.py`中给出的单属性测试代码。

不知道您说的“训练效果不太好”以及“没有效果”是什么意思。人脸属性编辑中，眼镜是一个比较难的属性，因为眼镜的结构性很强，而且去除墨镜等同于是一个inpainting任务，效果比其他属性稍差比较正常。以及另外一个可能的原因是样本的不平衡问题，也会导致生成质量稍差。

**Comment by VincentZgj** [comment]
非常感谢您的回复以及更正，以上方法都试过了，但是目前还是没有转换的效果，可能是我的代码还是有点问题，另外想请问下您的代码，batch_size必须设置成32吗，设置成1的时候，运行了6万次，人脸编辑失败。

**Comment by VincentZgj** [comment]
非常感谢您的回复以及更正，应该是数据集处理的问题，可能在一个batch_size中图片之间没有差异或者说差异，或者是您上述的问题，样本不均衡，导致属性差异学的不是很好，因此人脸属性编辑失败

**Comment by csmliu** [comment]
根据BigGAN，GAN里面应该是大batch会好一些，应该和这个是有一些关系的。如果大部分时候见的数据有且仅有不戴眼镜的，很可能会学不出来，所以建议增大戴墨镜图片的比重和增大batchsize
