### ISSUE TITLE
How to evaluate PSNR/SSIM？

### ISSUE THREAD

**Issue by guxiaowei1** [csmliu/STGAN#24]
please tell me How to evaluate PSNR/SSIM？

**Comment by csmliu** [comment]
Kindly refer to https://github.com/csmliu/STGAN/issues/20#issuecomment-534065361.

**Comment by guxiaowei1** [comment]
thank you very much for your kindly reply.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ming Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月27日(星期天) 中午11:31
收件人:&nbsp;"csmliu/STGAN"<STGAN@noreply.github.com&gt;;
抄送:&nbsp;"gxw"<514410699@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [csmliu/STGAN] How to evaluate PSNR/SSIM？ (#24)




Kindly refer to #20 (comment).
