### ISSUE TITLE
Error using RTX 2070

### ISSUE THREAD

**Issue by yasmeen90** [csmliu/STGAN#25]
Thank you for this work. I have a question about Gpu. how to train this code using Gpu i have Rtx 2070 and try to install tensorflow-gpu but there are error and when use tensorflow 2.0 also error. How to solve this problem because i need to use my gpu

**Comment by csmliu** [comment]
Hi, maybe you could try to install tensorflow 1.12. The code has been tested on r1.12.

**Comment by csmliu** [comment]
I'm going to close this issue, if your problem is not solved, please feel free to reopen it.
