### ISSUE TITLE
how to search that the epoch 139 is the best one?

### ISSUE THREAD

**Issue by guxiaowei1** [csmliu/STGAN#26]
excuse me, why u think that the epochf139 is the best one ? and how to search it ? try everything possible?! expect your reply, thank u!

**Comment by csmliu** [comment]
Sorry for the late response.
I trained the model for 200 epochs at first, and found that after 120 epochs the results are similar with minor changes, so I changed the number to 140 (not 139) to save time.

**Comment by guxiaowei1** [comment]
thank u for your reply。
