### ISSUE TITLE
season translation

### ISSUE THREAD

**Issue by guxiaowei1** [csmliu/STGAN#27]
hi，could u provide me the code and data about season translation,please。Nowadays，we have improved your work （STgan), and could we have a talk about the detail of this work? my wechat account is gxw18061037210.please,get in touch with me.thank u so much!

**Comment by CastellanLiu** [comment]
Sorry that I had no time to reply when seeing this issue, and was reminded by another issue just now.
My portable disk got broken when coming back to school, and the model and code for season translation was lost (and the data on the baidu server was also cleared).

I'm currently working on other projects, thus the plan to extend STGAN was delayed. After finishing the current project, I'll prepare a pytorch version (or maybe tf2.0 version), and both facial attribute editing and season translation models will be available. So sorry for the inconvenience.

BTW, we can talk on wechat and find what I can help.
