### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by shbnm21** [csmliu/STGAN#28]
Hello @csmliu 
  I have a question.I have converted the model into frozen_graph.pb how to check the generated model has the same accuracy as the original model?

Do u have any experience of tflite?
If yes, then I want to know,if I want to deploy the model on Android then can I use the .pb file directly or do I need to convert it into tflite?

**Comment by csmliu** [comment]
1. You could process the same image and see whether the output images are the same (or have minor difference due to computation accuracy).
2. Maybe you can convert the att_classification model into .pb file as well, and compare the overall manipulation accuracy.

**Comment by shbnm21** [comment]
Ok thank you for the quick reply.
