### ISSUE TITLE
Only using 1 GPU although I specified --gpu "0,1,2,3,4,5,6,7"

### ISSUE THREAD

**Issue by lishali** [csmliu/STGAN#3]
Hi Ming, I am trying to run training on a 8 GPU cluster and have changed the --gpu settings appropriately.  However I see that the training is still only using 1 GPU, namely "0".  I can dig deeper into how the device is being distributed into training, but am wondering if I just did something easily fixable.  Thanks!

**Comment by CastellanLiu** [comment]
Hi lishaili, I'm sorry that the current version only supports a single GPU device. In the future, we'll release a pytorch version which supports multi-gpu environment.

**Comment by csmliu** [comment]
Hi lishaili, I'm sorry that the current version only supports a single GPU device. In the future, we'll release a pytorch version which supports multi-gpu environment.

**Comment by lishali** [comment]
Good work on the current repo!  Looking forward to the Pytorch version.
