### ISSUE TITLE
Use of deprecated function caused error

### ISSUE THREAD

**Issue by lamozg6** [csmliu/STGAN#30]
scipy.misc.imsave has been deprecated in newer Scipy versions and on Ubuntu 18.04 (Scyipy version 1.3.3) it gives attribute error. You can change it by any other saving function, I used imageio.imwrite function with the same parameters (from imageio library).

**Comment by csmliu** [comment]
Thank you very much for appointing this out, I'll check whether the saved images by scipy and imageio are identical.
By the way, installing scipy v1.1 would solve this problem.
