### ISSUE TITLE
Attribution classification results of AttGAN

### ISSUE THREAD

**Issue by juicecwc** [csmliu/STGAN#31]
Hi, here is a question about the the attribution classification results of AttGAN in your paper.

Are the results tested on the released model of [AttGAN-Tensorflow](https://github.com/LynnHo/AttGAN-Tensorflow) ? Or you just retrain a new AttGAN model and test on it.

I test the [128x128 model](https://drive.google.com/file/d/1lcQ-ijNrGD4919eJ5Dv-7ja5rsx5p0Tp/view?usp=sharing) released by [AttGAN-Tensorflow](https://github.com/LynnHo/AttGAN-Tensorflow), and get different results from yours. As for your results, I refer to this file [quantitative.results.xlsx](https://github.com/csmliu/STGAN/files/3579879/quantitative.results.xlsx).

And the picture below shows the details.
![image](https://user-images.githubusercontent.com/20504381/75096432-82911880-55da-11ea-9808-8d0b754eabab.png)

**Comment by csmliu** [comment]
Hi, are you using att_classification provided in this repo?
I use the official model, but I remember that the authors of AttGAN have updated their pre-trained model. Which model from AttGAN are you using? I notice that there may be more than one models in their Google Drive, however, currently I have no access to Google Drive.

**Comment by csmliu** [comment]
Kindly refer to https://github.com/LynnHo/AttGAN-Tensorflow/issues/13.

**Comment by csmliu** [comment]
Hi, is it convenient for you to evaluate the model given in https://github.com/LynnHo/AttGAN-Tensorflow/tree/v1 (128_shortcut1_inject1_none.zip uploaded on June 7th, 2018)? Please follow the official instruction given by the authors to generate output images with code of that version, and use https://github.com/csmliu/STGAN/tree/master/att_classification for testing.

You know, the authors of AttGAN have uploaded more pretrained models and have updated the code recently. However, all these are done after the deadline of CVPR 2019 (Nov, 15th, 2018), so kindly use the same test setting with us to get the results.

Thanks!

**Comment by juicecwc** [comment]
Hi, thank you for your prompt reply! I will try it soon.
By the way, I am working on a research recently following your work. Is it convenient for you to add WeChat? We can communicate more conveniently. My wechat ID has been sent you by email. Thanks again!
