### ISSUE TITLE
generation attribute acc

### ISSUE THREAD

**Issue by Blue-Clean** [csmliu/STGAN#32]
hello,Could you please tell me the detailed data of IcGAN. Fadernet ,attgan and your STGAN? You only show a table without data, THANKS!

**Comment by csmliu** [comment]
Kindly refer to https://github.com/csmliu/STGAN/issues/18#issuecomment-528414039, or directly download the file https://github.com/csmliu/STGAN/files/3579879/quantitative.results.xlsx
