### ISSUE TITLE
Loading Pictures for pretrained model 

### ISSUE THREAD

**Issue by drd13** [csmliu/STGAN#33]
Hello,

I am trying to get the pretrained model working and running into some difficulties. In the repository you suggest that we should refer to the Attgan-tf repository for dataset preparation. However that repository seems to be using the non-alligned dataset and cropping it while you suggest to use the aligned. I was wondering if you could clarify what steps from that repository need to be taken in order to get the pretrained model working

**Comment by LynnHo** [comment]
@drd13 https://github.com/LynnHo/AttGAN-Tensorflow/tree/v1, the first version of AttGAN used the aligned one.
