### ISSUE TITLE
您好，我想请教一下关于预训练模型的问题

### ISSUE THREAD

**Issue by synge0718** [csmliu/STGAN#36]
在Github上提供的预训练模型是专门在CelebA数据集上进行14个属性转换的，如果我需要在其他的数据集上进行属性转换，我需要如何修改代码？这个预训练模型可以为其他数据集的属性转换重新训练吗？

**Comment by csmliu** [comment]
1. 如何修改代码
如果其他数据集同样是这十四个属性，并且是同样的对齐方式，那么可以直接使用，不过训练集CelebA以欧美明星为主，迁移到其他数据集可能不是很理想，建议重新训练；
如果属性不同，或者对齐方式不同/未对齐，建议重新训练，需要修改的地方包括：1）数据读取部分，包括数据处理和代码适配，2）属性修改，包括提供新数据集的属性文件（建议按照CelebA格式，或者调整代码）；
2. 预训练
如果数据集较为接近，可以作为预训练模型，否则意义不是很大，因为收敛还是比较快的；
如果属性发生变化，或者数据形式不同，不建议作为预训练模型。
