### ISSUE TITLE
Training time.

### ISSUE THREAD

**Issue by XijieJiao** [csmliu/STGAN#39]
According to the paper, you used an environment of 'Intel(R) Xeon(R) E3-1230v5 CPU 3.40GHz and Nvidia GTX1080Ti GPU' to train STGAN and your celeba dataset has 200K images. 
May I ask how long it takes you to train the whole network (I remember that your pretrained network was trained for 139 epochs)? Thank you.

**Comment by csmliu** [comment]
Sorry I forgot the training time, however you can refer to the previous issue (https://github.com/csmliu/STGAN/issues/6#issuecomment-498918673), it is about 30 minutes per epoch.
