### ISSUE TITLE
如何選取眼鏡樣式?

### ISSUE THREAD

**Issue by denny3366978** [csmliu/STGAN#41]
您好~
我在ATTGAN裡面有看到可以選擇眼鏡的樣式，
而STGAN是由ATTGAN更改的，
請問這個程式可以透過任何方法自由選取眼鏡樣式嗎?
希望能得到您的幫助，非常感謝!

**Comment by csmliu** [comment]
您好，抱歉STGAN是基于AttGAN的会议版本做的，没有加选择样式的实验，而AttGAN期刊版本中加了样式控制，但也没有给该部分的的代码，所以您有兴趣可以问AttGAN的作者。
据我与AttGAN作者交流所知，AttGAN中的属性样式控制，与InfoGAN类似，供您参考。

**Comment by denny3366978** [comment]
了解，非常感謝您~
