### ISSUE TITLE
Train STGAN using fewer attributes

### ISSUE THREAD

**Issue by XijieJiao** [csmliu/STGAN#42]
Hi, thank you for sharing the code. I am now trying to train stgan with only 24 attributes. I have the aligned dataset and the corresponding labelset. Which part in your code do I need to change?

Thank you.

**Comment by csmliu** [comment]
It's a pity that I haven't received the emails about this repo for a long time, and didn't notice the issue, so sorry for the extremely late reply.

I remember that the code supports different number of attributes, please refer to [the option in train.py](https://github.com/csmliu/STGAN/blob/master/train.py#L42-L45) for a reference.

I'm going to close this issue. If you have any other questions, please feel free to reopen the issue, or open a new one.
