### ISSUE TITLE
鬍子的濃密度

### ISSUE THREAD

**Issue by denny3366978** [csmliu/STGAN#44]
您好!
我做了添加鬍子的測試，請問有任何方法選取鬍子的樣式或是調整它的濃密強度嗎?
感謝您的幫助!

**Comment by csmliu** [comment]
It's a pity that I haven't received the emails about this repo for a long time, and didn't notice the issue, so sorry for the extremely late reply.

To change the style of the beard, please refer to [AttGAN](https://github.com/LynnHo/AttGAN-Tensorflow), which is not included in this repo.
For changing the density, you can modify [the options in test.py](https://github.com/csmliu/STGAN/blob/master/test.py#L35-L39)

I'm going to close this issue. If you have any other questions, please feel free to reopen the issue, or open a new one.
