### ISSUE TITLE
How can i use pre-trained model

### ISSUE THREAD

**Issue by Sepideh-Rezaeirad** [csmliu/STGAN#45]
Hello,

First of all, Thank you for providing your code publicly.

Secondly, How can i use the pre-trained model to see the output of the network.

Many thanks.

**Comment by csmliu** [comment]
It's a pity that I haven't received the emails about this repo for a long time, and didn't notice the issue, so sorry for the extremely late reply.

To use the pre-trained model, please follow the instructions given in the README, and show the specific problems encountered.

I'm going to close this issue. If you have any other questions, please feel free to reopen the issue, or open a new one.
