### ISSUE TITLE
Not getting the proper bald image

### ISSUE THREAD

**Issue by abd-ozos** [csmliu/STGAN#46]
Hey, Thanks for your wonderful work. I am not getting a proper bald image in the output as given by you in the paper. can you please guide me to improve the accuracy of the bald image in the output

**Comment by csmliu** [comment]
It's a pity that I haven't received the emails about this repo for a long time, and didn't notice the issue, so sorry for the extremely late reply.

Maybe you can adjust the `--test_int` parameter.
For a further improvement, adding a facial parsing to the model may help.

I'm going to close this issue. If you have any other questions, please feel free to reopen the issue, or open a new one.
