### ISSUE TITLE
KeyError: 'Ours'

### ISSUE THREAD

**Issue by quancunzuicuo** [csmliu/STGAN#49]
请问我在运行show_images.py时遇到KeyError: 'Ours'该如何解决

**Comment by quancunzuicuo** [comment]
报错信息：
Can't open 182638 of Ours
Can't open 182638 of rec_Ours
Traceback (most recent call last):
  File "show_images.py", line 302, in <module>
    mywin = MyWindow()
  File "show_images.py", line 108, in __init__
    self.cur_imgs = self.process_img(self.cur_img)
  File "show_images.py", line 201, in process_img
    imgs[cat].append(wimg.crop(crop_rec_dict[cat]))
KeyError: 'Ours'
源代码应该是200和107，我在之前加了一行改了list_attr_celeba.txt的路径

**Comment by csmliu** [comment]
这个代码是在运行完之后，展示结果所用。根据您提供的信息，200行中两处可能报错的地方，imgs[cat]和crop_rec_dict[cat]，第二处因为已经预定义好，如果您没有修改68行，就不可能出错，所以应当是第一处报错。而这里与173-191行代码相关，而可能跳过186行的只有182行，因此，请检查命令行中是否输出了如181行所示的提示信息。

TL;DR. 请检查是否按照程序对应格式，运行主程序代码生成结果

**Comment by quancunzuicuo** [comment]
谢谢，已解决
