### ISSUE TITLE
help bug

### ISSUE THREAD

**Issue by l1uw3n** [csmliu/STGAN#5]
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
NOTE: Initializing all parameters...
Traceback (most recent call last):
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [height must be >= target + offset.]
         [[{{node crop_to_bounding_box/Assert_1/Assert}} = Assert[T=[DT_STRING], summarize=3](crop_to_bounding_box/GreaterEqual_1, crop_to_bounding_box/Assert_1/Assert/data_0)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[32,128,128,3], [32,13]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node RandomShuffle/_15}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_156_RandomShuffle", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 337, in <module>
    d_summary_opt, _ = sess.run([d_summary, d_step], feed_dict={lr: lr_ipt})
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/lw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [height must be >= target + offset.]
         [[{{node crop_to_bounding_box/Assert_1/Assert}} = Assert[T=[DT_STRING], summarize=3](crop_to_bounding_box/GreaterEqual_1, crop_to_bounding_box/Assert_1/Assert/data_0)]]
         [[node IteratorGetNext (defined at /home/lw/workspace/STGAN/data.py:102)  = IteratorGetNext[output_shapes=[[32,128,128,3], [32,13]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node RandomShuffle/_15}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_156_RandomShuffle", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Model is saved at ./output/128/checkpoints/Epoch_(0)_(1of947).ckpt!

**Comment by l1uw3n** [comment]
@CastellanLiu 
Thank you for your answer. I later found out that I mixed my own data in CelebA. The size of the mixed image is too small to cause the above bug. In addition, I have modified some of the code to suit my work. Thank you for your work. Currently I am trying to run this project on other datasets, such as seasonal conversions, but it is not very smooth. Can you create another branch of seasonal conversion?

**Comment by CastellanLiu** [comment]
Sorry that the season translation code are too messy (and there are too many versions), and currently I have no time to sort it out. We will release a season translation code in the pytorch version.
