### ISSUE TITLE
stargan's reconstructed images

### ISSUE THREAD

**Issue by quancunzuicuo** [csmliu/STGAN#53]
怎么获得测试阶段的stargan的reconstructed images

**Comment by CastellanLiu** [comment]
直接输入数据集提供的label

**Comment by quancunzuicuo** [comment]
stargan提供的测试指令是
$ python main.py --mode test --dataset CelebA --image_size 128 --c_dim 5 \
                 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young \
                 --model_save_dir='stargan_celeba_128/models' \
                 --result_dir='stargan_celeba_128/results'
可以直接修改指令得到重构图片吗，还是要改源代码

**Comment by csmliu** [comment]
我印象中应该是修改了代码，参考StarGAN官方代码，如果selected_attr是空的，那么最终的c_trg_list（173行），也会是空的，所以需要对代码进行简单的修改
https://github.com/yunjey/stargan/blob/master/solver.py#L159-L168

**Comment by quancunzuicuo** [comment]
你之前改过的solver.py还在吗，我发现不止得到重构图片需要修改，得到多属性编辑结果也要一定的修改

**Comment by csmliu** [comment]
抱歉，从百度实习回来之后，移动硬盘坏了，没有这部分模型和代码了

**Comment by quancunzuicuo** [comment]
可惜，但还是感谢你及时的回答！
