### ISSUE TITLE
stargan pretrained model

### ISSUE THREAD

**Issue by quancunzuicuo** [csmliu/STGAN#54]
你好，stargan官方提供的模型只包括5个属性，更多属性好像还要自己训练，请问STGAN论文里用到的stargan预训练模型哪里能下载吗

**Comment by csmliu** [comment]
抱歉，我从百度实习回来之后移动硬盘坏了，StarGAN改的代码和训练的模型在里面，没恢复出来，现在没有了

**Comment by quancunzuicuo** [comment]
可惜，那我问问AttGAN的作者还有没有保存，谢谢你的回答！
