### ISSUE TITLE
difference face position

### ISSUE THREAD

**Issue by quancunzuicuo** [csmliu/STGAN#55]
你好，我将AttGAN运行出来的结果和STGAN的结果对比了下，发现结果图片人脸的位置和比例有所差别(不是实现效果的差异)，达不到STGAN论文里那样的对比效果，两者都是用img_align_celeba的图片，是两者对原始图片的处理有所差别吗？我该如何让AttGAN运行出的结果能和STGAN对比？

**Comment by csmliu** [comment]
请参考下面链接的代码，STGAN与AttGAN，对于128x128图像的预处理应该是一致的，您可以检查使用的图像和尺寸是否一致
https://github.com/csmliu/STGAN/blob/master/data.py#L165-L173
之前AttGAN更新了代码，您可以尝试使用第一版代码，看输出结果是否一致，如果第一版一致，而第二版不一致，请咨询AttGAN作者关于新版本代码的问题
https://github.com/LynnHo/AttGAN-Tensorflow/tree/v1

**Comment by quancunzuicuo** [comment]
第一版复现出来的结果位置就正常了，感谢你的回答！
