### ISSUE TITLE
Setting for 256x256 images.

### ISSUE THREAD

**Issue by songquanpeng** [csmliu/STGAN#56]
Hello, i want to ask what's your recommand setting for 256x256 image on CelebA-HQ. 

Does it okay to use the setting for 384x384 image? 

Thx in advance.

**Comment by CastellanLiu** [comment]
Using the setting for 128x128 images may be better since the setting for 384x384 considers more about computation amount and memory usage.

**Comment by songquanpeng** [comment]
Thx for you reply. Do you think 384x384's setting will have better performance then 128x128's setting on 256x256?

**Comment by CastellanLiu** [comment]
I don't think so. Because the setting for 384x384 reduces the channel number of the layers to achieve an acceptable computation amount on a single 1080 GPU. If better GPUs are available now, I recommend using the setting for 128x128.

**Comment by songquanpeng** [comment]
Thx, i am clear now. 
Before that i thought the model under 384x384's setting has better learning capacity.  I should carefully check the code before asking. 
Thx again! It really help.
