### ISSUE TITLE
Train my dataset very slowly

### ISSUE THREAD

**Issue by wapleeeeee** [csmliu/STGAN#6]
Thanks for sharing the model!
I reconstructed the data.py with my dataset(80K training images), and used this framework, everything went well except the time cost. The model spent nearly one day training only an epoch with two gpus. I wonder how many gpus you have used in your experiments and how much time have you spent.
Thanks a lot!

**Comment by CastellanLiu** [comment]
As stated in the paper, I used a PC equipped with an Intel E3-1230v5 and a single 1080Ti. It takes about 30 minutes to train an epoch.

**Comment by wapleeeeee** [comment]
My fault! I used tensorflow-cpu by default, and now it works!
This issue seems very ridiculous, since I seldom use tensorflow. So I wonder if there will be a pytorch release for your great work.

**Comment by CastellanLiu** [comment]
Yes, there will be a pytorch version with more features.

**Comment by wapleeeeee** [comment]
Looking forward to it!
