### ISSUE TITLE
Can I get the attributes like the face direction?

### ISSUE THREAD

**Issue by c1a1o1** [csmliu/STGAN#8]
Can I get the attributes like the face direction?

**Comment by csmliu** [comment]
Sorry, CelebA dataset does not provide face direction labels. Multi-PIE may be a good choice for you (with 0°, ±30°, ±60° and ±90° images of the same person).

**Comment by csmliu** [comment]
If you really want to get face direction of the CelebA dataset (not aligned), I recommend [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace).
