### ISSUE TITLE
How is the list_attr_celeba.txt file generated?

### ISSUE THREAD

**Issue by AdarshMJ** [csmliu/STGAN#9]
If I want to change the dataset and train it, how is the list_attr_celeba.txt file created?

**Comment by csmliu** [comment]
Just as the provided list_attr_celeba.txt, and you should correspondingly modify the `CelebA` class in data.py, as well as the attributes.

**Comment by AdarshMJ** [comment]
So after modifying the CelebA class in data.py, running this code will give me the text file?

**Comment by csmliu** [comment]
No, you should prepare the text file as `list_attr_celeba.txt` by yourself if you want to use a custom dataset, and you should also write a class like `CelebA` since the settings of `CelebA` are prepared only for `CelebA` dataset.

**Comment by AdarshMJ** [comment]
Oh okay got it. Thank You!
Any specific timeline when the PyTorch version of season conversion code will be available?

**Comment by csmliu** [comment]
So sorry, but not recently.
